cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove, cart_recalculate


urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<str:product_id>/<str:product_age>/<str:product_container>/<str:product_price>',
         cart_add, name='cart_add'),
    path('remove/<str:product_id>/<str:product_age>/<str:product_container>',
         cart_remove, name='cart_remove'),
    path('recalculate/<str:product_id>/<str:product_age>/<str:product_container>/<str:quantity>',
         cart_recalculate, name='cart_recalculate')
]

ksu_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('account/', include('account.urls')),
    path('', include('main_app.urls')),
]

orders/urls.py
from django.urls import path
from .views import order_create


urlpatterns = [
    path('create/', order_create, name='order_create'),
]

orders/models.py
from django.contrib.auth import get_user_model
from django.db import models
from main_app.models import Product, ProductPrice
from django.contrib import admin

User = get_user_model()


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_COMPLETED = 'completed'
    STATUS_CANCELED = 'canceled'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Нове замовлення'),
        (STATUS_IN_PROGRESS, 'В обробці'),
        (STATUS_COMPLETED, 'Виконано'),
        (STATUS_CANCELED, 'Скасовано')
    )

    DELIVERY_TYPE_PICK_UP = 'pick_up'
    DELIVERY_TYPE_NOVA_P = 'delivery_nova_p'
    DELIVERY_TYPE_UKR_P = 'delivery_ukr_p'

    DELIVERY_TYPE_CHOICES = (
        (DELIVERY_TYPE_PICK_UP, 'Самовивіз'),
        (DELIVERY_TYPE_NOVA_P, 'Новою поштою'),
        (DELIVERY_TYPE_UKR_P, 'Укрпоштою'),
    )

    PAYMENT_TYPE_CASH = 'cash'
    PAYMENT_TYPE_CARD = 'card'

    PAYMENT_TYPE_CHOICES = (
        (PAYMENT_TYPE_CASH, 'Накладеним платежем'),
        (PAYMENT_TYPE_CARD, 'Оплата на карту')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             verbose_name='Користувач', related_name='orders')
    first_name = models.CharField(max_length=50, verbose_name="Ім'я")
    last_name = models.CharField(max_length=50, verbose_name='Прізвище')
    phone_number = models.CharField(max_length=15, verbose_name='Номер телефону')
    email = models.EmailField(verbose_name='Эл. пошта')
    city = models.CharField(max_length=100, verbose_name='Місто')
    address = models.CharField(max_length=250, verbose_name='Адреса')
    postal_code = models.CharField(max_length=20, verbose_name='Поштовий індекс')
    created = models.DateField(auto_now_add=True, verbose_name='Створено')
    updated = models.DateTimeField(auto_now=True, verbose_name='Оновлено')
    consignment_note = models.CharField(default='', max_length=25, verbose_name='ТТН')
    paid = models.BooleanField(default=False, verbose_name='Сплачено')
    comment = models.TextField(verbose_name='Коментар до замовлення', blank=True)
    delivery_type = models.CharField(
        max_length=100,
        verbose_name='Тип доставки',
        choices=DELIVERY_TYPE_CHOICES,
    )
    status_order = models.CharField(
        max_length=100,
        verbose_name='Статус замовлення',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    payment_type = models.CharField(
        max_length=100,
        verbose_name='Тип оплати',
        choices=PAYMENT_TYPE_CHOICES,
        default=PAYMENT_TYPE_CARD
    )

    class Meta:
        ordering = ('-id',)
        verbose_name = 'замовлення'
        verbose_name_plural = 'замовлення'

    def __str__(self):
        return f'№ {self.id} від {self.created}'

    @admin.display(description='сума')
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE, verbose_name='Замовлення')
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE, verbose_name='Продукт')
    product_age = models.CharField(max_length=100, verbose_name='Вік рослини')
    product_container = models.CharField(max_length=100, verbose_name='Розмір контейнеру')
    price = models.DecimalField(default=0, max_digits=10, decimal_places=0, verbose_name='Ціна')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Кількість')

    class Meta:
        verbose_name = 'Предмети замовлення'
        verbose_name_plural = 'Предмети замовлення'

    def __str__(self):
        return ''

    def get_cost(self):
        return self.price * self.quantity

orders/views.py
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, get_object_or_404

from account.models import Profile
from .models import Order, OrderItem
from cart.cart import Cart
from .tasks import order_created
from account.tasks import user_register

User = get_user_model()


def order_create(request):

    cart = Cart(request)
    if request.method == 'POST' and cart:
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        phone_number = request.POST.get('phone_number')
        email = request.POST.get('email')
        city = request.POST.get('city')
        address = request.POST.get('address')
        postal_code = request.POST.get('postal_code')
        comment = request.POST.get('comment')
        delivery_type = request.POST.get('delivery_type')
        payment_type = request.POST.get('payment_type')
        if request.user.is_authenticated:
            user = request.user
        else:
            # automatic user registration at checkout
            if not User.objects.filter(username=email):
                new_user = User.objects.create(
                    username=email,
                    first_name=first_name,
                    last_name=last_name,
                    email=email,
                    is_active=False
                )
                new_user.set_unusable_password()
                new_user.save()
                Profile.objects.create(
                    user=new_user,
                    phone_number=phone_number,
                    city=city,
                    address=address,
                    postal_code=postal_code
                )
                current_site = get_current_site(request)
                use_https = request.is_secure()
                user_register.delay(new_user.email, current_site.domain, use_https)
                user = new_user
            else:
                user = get_object_or_404(User, username=email)
        order = Order.objects.create(
            user=user,
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,
            email=email,
            city=city,
            address=address,
            postal_code=postal_code,
            comment=comment,
            delivery_type=delivery_type,
            payment_type=payment_type,
        )
        for item in cart:
            OrderItem.objects.create(order=order,
                                     product=item['product'],
                                     product_age=item['product_age'].get_product_age_display(),
                                     product_container=item['product_container'].get_product_container_display(),
                                     price=item['price'],
                                     quantity=item['quantity']
                                     )
        # clearing the cart
        cart.clear()
        # start an asynchronous task
        order_created.delay(order.id)
        return render(request, 'created.html', {'order': order})
    else:
        return render(request, 'create.html', {'cart': cart})

orders/templates/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}Оформлення замовлення{% endblock %}

{% block content %}
    <div class="container mt-10 mb-3 flex-grow-1">
        {% if cart %}
        <h1>Оформлення замовлення</h1>
        <div class="row mt-3">
            <div class="col-lg-7">
                <form action="." method="post">
                    {% csrf_token %}
                    <div class="form-outline">
                      <input type="text" id="first_name" class="form-control" name="first_name" required
                             {% if request.user.is_authenticated %} value="{{ request.user.first_name }}" {% endif %}
                      />
                      <label class="form-label" for="first_name">Ім'я</label>
                    </div>
                    <div class="form-outline mt-3">
                      <input type="text" id="last_name" class="form-control" name="last_name" required
                             {% if request.user.is_authenticated %} value="{{ request.user.last_name }}" {% endif %}
                      />
                      <label class="form-label" for="last_name">Прізвище</label>
                    </div>
                    <div class="form-outline mt-3">
                      <input type="tel" id="phone_number" class="form-control" pattern="\+38\d{10}"
                             placeholder="+380501111111" name="phone_number" required
                             {% if request.user.is_authenticated %} value="{{ request.user.profile.phone_number }}"
                             {% else %} value="+380" {% endif %}
                      />
                      <label class="form-label" for="phone_number">Номер телефону</label>
                    </div>
                    <div class="form-outline mt-3">
                      <input type="email" id="email" class="form-control" name="email" required
                             {% if request.user.is_authenticated %}
                             value="{{ request.user.email }}"
                             {% endif %}
                      />
                      <label class="form-label" for="email">Эл. пошта</label>
                    </div>
                    <div class="form-outline mt-3">
                      <input type="text" id="city" class="form-control" name="city" required
                             {% if request.user.is_authenticated %} value="{{ request.user.profile.city }}" {% endif %}
                      />
                      <label class="form-label" for="city">Місто</label>
                    </div>
                    <div class="form-outline mt-3">
                      <input type="text" id="address" class="form-control" name="address" required
                             {% if request.user.is_authenticated %}
                             value="{{ request.user.profile.address }}"
                             {% endif %}
                      />
                      <label class="form-label" for="address">Адреса</label>
                    </div>
                    <div class="form-outline mt-3">
                      <input type="text" id="postal_code" class="form-control" name="postal_code" required
                             {% if request.user.is_authenticated %}
                             value="{{ request.user.profile.postal_code }}"
                             {% endif %}
                      />
                      <label class="form-label" for="postal_code">Поштовий індекс</label>
                    </div>
                    <select class="form-select mt-3" name="delivery_type" required>
                        <option value="" disabled selected>Виберіть тип доставки</option>
                        <option value="pick_up">Самовивіз</option>
                        <option value="delivery_nova_p">Новою поштою</option>
                        <option value="delivery_ukr_p">Укрпоштою</option>
                    </select>
                    <select class="form-select mt-3" name="payment_type" required>
                        <option value="" disabled selected>Виберіть тип оплати</option>
                        <option value="cash">Накладеним платежем</option>
                        <option value="card">Оплата на карту</option>
                    </select>
                    <div class="form-outline mt-3">
                      <textarea type="text" id="comment" name="comment" class="form-control"></textarea>
                      <label class="form-label" for="comment">Коментар до замовлення</label>
                    </div>
                    <input class="mt-3 btn btn-success btn-block" type="submit" value="Зробити замовлення">
                </form>
            </div>
            <div class="col-md-6 col-lg-5 col-xl-4 mt-3 mt-lg-0">
              <div class="border px-3">
                <div class="border-bottom">
                  <p class="text-uppercase mb-0 py-3"><strong>Ваше замовлення</strong></p>
                </div>
                <div class="pt-3">
                    <div class="border-bottom">
                      <ul>
                        {% for item in cart %}
                            <li>
                                {{ item.quantity }} шт {{ item.product }}
                                {{ item.product_age.get_product_age_display }}
                                {{ item.product_container.get_product_container_display }}
                                <span>{{ item.total_price }} грн</span>
                            </li>
                        {% endfor %}
                      </ul>
                    </div>
                      <div class="d-flex justify-content-between pt-3">
                           <p class="text-uppercase"><strong>Всього</strong></p>
                           <p class="font-weight-bold">{{ cart.get_total_price }} грн</p>
                      </div>
                </div>
              </div>
            </div>
        </div>
        {% else %}
            <h3 class="text-center">Нажаль Ваш кошик порожній. Зробіть будь-ласка замовлення</h3>
        {% endif %}
    </div>

{% endblock %}

orders/templates/created.html
{% extends "base.html" %}

{% block title %}Дякуємо за замовлення{% endblock %}

{% block content %}
    <div class="container mt-10 mb-3 justify-content-center">
        <div>
            <h1>Дякуємо</h1>
            <p>Ваше замовлення успішно оформлене. Номер Вашого замовлення
                <strong>{{ order.id }}</strong>.
            </p>
            <p>З повагою, інтернет магазин "Par.ost.ok"</p>
        </div>
        <div class="mt-5">
            {% if order.payment_type == 'card' %}
            <p>Карта приватбанк ******** на ім'я Гаїна О.С. (ФОП)</p>
            <p>Сума до сплати: {{ order.get_total_cost }} грн</p>
            <p>Призначення платежу: № замовлення</p>
            <p>Рахунок дійсний протягом одного дня</p>
            <br>
            {% endif %}
            <p><span class="me-3 text-black-50">Ім'я</span> {{ order.first_name }}</p>
            <p><span class="me-3 text-black-50">Прізвище</span> {{ order.last_name }}</p>
            <p><span class="me-3 text-black-50">Номер телефону</span> {{ order.phone_number }}</p>
            <p><span class="me-3 text-black-50">Эл. пошта</span> {{ order.email }}</p>
            <p><span class="me-3 text-black-50">Місто</span> {{ order.city }}</p>
            <p><span class="me-3 text-black-50">Адреса</span> {{ order.address }}</p>
            <p><span class="me-3 text-black-50">Поштовий індекс</span> {{ order.postal_code }}</p>
            <p><span class="me-3 text-black-50">Тип доставки</span> {{ order.get_delivery_type_display }}</p>
            <p><span class="me-3 text-black-50">Тип оплати</span> {{ order.get_payment_type_display }}</p>
            {% if order.comment %}
                <p>Коментар {{ order.comment }}</p>
            {% endif %}
            <div class="mt-3">
                <h5><strong>Замовлення</strong></h5>
                {% for item in order.items.all %}
                <div class="row pt-2">
                    <div class="col-lg-2">
                        <a href="{{ item.product.get_absolute_url }}">
                            <img width="110" height="110" src="/media/{{ item.product.images.first }}"
                                 alt="{{ item.product }}">
                        </a>
                    </div>
                    <div class="col-lg-6">
                        <a class="created" href="{{ item.product.get_absolute_url }}">
                            {{ item.product }}<br>
                            <small>{{ item.product_age }}
                            {{ item.product_container }}</small>
                            <br>
                            <small>{{ item.price }} грн</small>
                        </a>
                    </div>
                    <div class="col-6 col-lg-2">
                        <br class="d-lg-none">
                        Кількість
                        <br>
                        {{ item.quantity }} шт
                    </div>
                    <div class="col-6 col-lg-2">
                        <br class="d-lg-none">
                        Сума
                        <br>
                        {{ item.get_cost }} грн
                    </div>
                </div>
                {% endfor %}
                <div class="text-end">
                    Доставка по Україні <strong>за тарифами перевізника</strong>
                </div>
                <div class="text-end">
                    <span>Всього</span>
                    <span>{{ order.get_total_cost }} грн</span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

orders/templates/order_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>

<body>
    <table width="800" cellspacing="0" cellpadding="0" border="0" align="center"
           style="font:14px Arial,Helvetica,sans-serif">
        <tbody>
            <tr>
                <td width="100%" style="height: 92px; border-bottom: 3px solid #737373">
                    <table width="100%" cellspacing="0" cellpadding="0" border="0">
                        <tbody>
                            <tr>
                                <td style="font-size: 20px;font-weight: bold;padding-top: 6px;">
                                    <a style="color: #000;text-decoration: none" href="#">Par.ost.ok</a>
                                </td>
                                <td style="color: #000;font-size: 16px;font-weight: bold;padding-top: 6px;text-align: right">
                                    <div style="padding-left: 18px;float: right;">
                                        <a style="color: #000;text-decoration: none" href="tel:+380989192030">
                                            +38 098 919 20 30
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding: 22px 0;color: #000;font-size: 16px;line-height: 1.5">
                    <div style="margin-bottom: 9px;font-size: 20px;font-weight: bold;color: #231f20">
                        Номер замовлення {{ order_id }}
                    </div>
                    {% if order.payment_type == 'card' %}
                    <p>Карта приватбанк ******** на ім'я Гаїна О.С. (ФОП)</p>
                    <p>Сума до сплати: {{ order.get_total_cost }} грн</p>
                    <p>Призначення платежу: № замовлення</p>
                    <p>Рахунок дійсний протягом одного дня</p>
                    <br>
                    {% endif %}
                    <p>З повагою, інтернет магазин "Par.ost.ok"</p>
                    <div style="padding-bottom: 25px">
                        <table width="100%" cellspacing="0" cellpadding="0" border="0" style="font-size: 16px">
                            <tbody>
                                <tr>
                                    <td width="160" style="padding: 6px 30px 6px 0;color: #8d8d8d; vertical-align: top">
                                        Ім'я
                                    </td>
                                    <td style="padding: 6px 0 6px 0">
                                        {{ order.first_name }}
                                    </td>
                                </tr>
                                <tr>
                                    <td width="160" style="padding: 6px 30px 6px 0;color: #8d8d8d; vertical-align: top">
                                        Прізвище
                                    </td>
                                    <td style="padding: 6px 0 6px 0">
                                        {{ order.last_name }}
                                    </td>
                                </tr>
                                <tr>
                                    <td width="160" style="padding: 6px 30px 6px 0;color: #8d8d8d; vertical-align: top">
                                        Номер телефону
                                    </td>
                                    <td style="padding: 6px 0 6px 0">
                                        {{ order.phone_number }}
                                    </td>
                                </tr>
                                <tr>
                                    <td width="160" style="padding: 6px 30px 6px 0;color: #8d8d8d; vertical-align: top">
                                        Ел. пошта
                                    </td>
                                    <td style="padding: 6px 0 6px 0">
                                        {{ order.email }}
                                    </td>
                                </tr>
                                <tr>
                                    <td width="160" style="padding: 6px 30px 6px 0;color: #8d8d8d; vertical-align: top">
                                        Місто
                                    </td>
                                    <td style="padding: 6px 0 6px 0">
                                        {{ order.city }}
                                    </td>
                                </tr>
                                <tr>
                                    <td width="160" style="padding: 6px 30px 6px 0;color: #8d8d8d; vertical-align: top">
                                        Адреса
                                    </td>
                                    <td style="padding: 6px 0 6px 0">
                                        {{ order.address }}
                                    </td>
                                </tr>
                                <tr>
                                    <td width="160" style="padding: 6px 30px 6px 0;color: #8d8d8d; vertical-align: top">
                                        Поштовий індекс
                                    </td>
                                    <td style="padding: 6px 0 6px 0">
                                        {{ order.postal_code }}
                                    </td>
                                </tr>
                                <tr>
                                    <td width="160" style="padding: 6px 30px 6px 0;color: #8d8d8d; vertical-align: top">
                                        Тип доставки
                                    </td>
                                    <td style="padding: 6px 0 6px 0">
                                        {{ order.get_delivery_type_display }}
                                    </td>
                                </tr>
                                <tr>
                                    <td width="160" style="padding: 6px 30px 6px 0;color: #8d8d8d; vertical-align: top">
                                        Тип оплати
                                    </td>
                                    <td style="padding: 6px 0 6px 0">
                                        {{ order.get_payment_type_display }}
                                    </td>
                                </tr>
                                {% if order.comment %}
                                <tr>
                                    <td width="160" style="padding: 6px 30px 6px 0;color: #8d8d8d; vertical-align: top">
                                        Коментар
                                    </td>
                                    <td style="padding: 6px 0 6px 0">
                                        {{ order.comment }}
                                    </td>
                                </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                    <div style="padding-bottom: 11px;font-weight: bold;font-size: 20px;color: #000">
                        Замовлення
                    </div>
                    <table width="100%" cellspacing="0" cellpadding="0" border="0"
                           style="font-size: 14px;border-top: 1px solid #ededed;color: #000">
                        <tbody>
                            {% for item in order.items.all %}
                            <tr style="border-bottom: 1px solid #ededed">
                                <td width="110" height="110" style="border-bottom: 1px solid #ededed;text-align: center">
                                    <a href="{{ item.product.get_absolute_url }}">
                                        <img width="110" height="110" src="/media/{{ item.product.images.first }}"
                                             alt="{{ item.product }}">
                                    </a>
                                </td>
                                <td width="320" style="border-bottom: 1px solid #ededed; padding: 15px">
                                    <div style="margin-bottom: 10px;font-size: 16px">
                                        <a style="text-decoration: none; color: black" href="{{ item.product.get_absolute_url }}">
                                            {{ item.product }}<br>
                                            <small>{{ item.product_age }}
                                            {{ item.product_container }}</small>
                                            <br>
                                            <small>{{ item.price }} грн</small>
                                        </a>
                                    </div>
                                </td>
                                <td style="border-bottom: 1px solid #ededed">
                                    <div>
                                        <p>Кількість</p>
                                        <p>{{ item.quantity }} шт</p>
                                    </div>
                                </td>
                                <td style="border-bottom: 1px solid #ededed">
                                    <div style="text-align: right">
                                        <p>Сума</p>
                                        <p>{{ item.get_cost }} грн</p>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <td colspan="4"
                                    style="text-align: right; border-bottom: 1px solid #ededed;padding: 15px;font-size: 16px">
                                    <div>Доставка по Україні за тарифами перевізника</div>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="4" style="padding: 15px 0;text-align: right">
                                    <span style="padding-right: 15px">Всього</span>
                                    <span style="font-size: 24px;font-weight: bold">
                                        {{ order.get_total_cost }} грн
                                    </span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding: 23px 0 21px;border-top: 1px solid #a5a5a5;">
                    <table width="100%" style="font: 12px Arial,Helvetica,sans-serif;color: #8d8d8d">
                        <tbody>
                            <tr>
                                <td style="font-size: 14px">
                                    <div>Par.ost.ok</div>
                                    <div>+38 098 919 20 30</div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</body>

</html>