cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove, cart_recalculate


urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<str:product_id>/<str:product_age>/<str:product_container>/<str:product_price>',
         cart_add, name='cart_add'),
    path('remove/<str:product_id>/<str:product_age>/<str:product_container>',
         cart_remove, name='cart_remove'),
    path('recalculate/<str:product_id>/<str:product_age>/<str:product_container>/<str:quantity>',
         cart_recalculate, name='cart_recalculate')
]

ksu_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('account/', include('account.urls')),
    path('', include('main_app.urls')),
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.contrib.auth import get_user_model
from django.db import models
from main_app.models import Product, ProductPrice
from django.contrib import admin

User = get_user_model()


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_COMPLETED = 'completed'
    STATUS_CANCELED = 'canceled'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Нове замовлення'),
        (STATUS_IN_PROGRESS, 'В обробці'),
        (STATUS_COMPLETED, 'Виконано'),
        (STATUS_CANCELED, 'Скасовано')
    )

    DELIVERY_TYPE_PICK_UP = 'pick_up'
    DELIVERY_TYPE_NOVA_P = 'delivery_nova_p'
    DELIVERY_TYPE_UKR_P = 'delivery_ukr_p'

    DELIVERY_TYPE_CHOICES = (
        (DELIVERY_TYPE_PICK_UP, 'Самовивіз'),
        (DELIVERY_TYPE_NOVA_P, 'Новою поштою'),
        (DELIVERY_TYPE_UKR_P, 'Укрпоштою'),
    )

    PAYMENT_TYPE_CASH = 'cash'
    PAYMENT_TYPE_CARD = 'card'

    PAYMENT_TYPE_CHOICES = (
        (PAYMENT_TYPE_CASH, 'Накладеним платежем'),
        (PAYMENT_TYPE_CARD, 'Оплата на карту')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             verbose_name='Користувач', related_name='orders')
    first_name = models.CharField(max_length=50, verbose_name="Ім'я")
    last_name = models.CharField(max_length=50, verbose_name='Прізвище')
    phone_number = models.CharField(max_length=15, verbose_name='Номер телефону')
    email = models.EmailField(verbose_name='Эл. пошта')
    city = models.CharField(max_length=100, verbose_name='Місто')
    address = models.CharField(max_length=250, verbose_name='Адреса')
    postal_code = models.CharField(max_length=20, verbose_name='Поштовий індекс')
    created = models.DateField(auto_now_add=True, verbose_name='Створено')
    updated = models.DateTimeField(auto_now=True, verbose_name='Оновлено')
    consignment_note = models.CharField(default='', max_length=25, verbose_name='ТТН')
    paid = models.BooleanField(default=False, verbose_name='Сплачено')
    comment = models.TextField(verbose_name='Коментар до замовлення', blank=True)
    delivery_type = models.CharField(
        max_length=100,
        verbose_name='Тип доставки',
        choices=DELIVERY_TYPE_CHOICES,
    )
    status_order = models.CharField(
        max_length=100,
        verbose_name='Статус замовлення',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    payment_type = models.CharField(
        max_length=100,
        verbose_name='Тип оплати',
        choices=PAYMENT_TYPE_CHOICES,
        default=PAYMENT_TYPE_CARD
    )

    class Meta:
        ordering = ('-id',)
        verbose_name = 'замовлення'
        verbose_name_plural = 'замовлення'

    def __str__(self):
        return f'№ {self.id} від {self.created}'

    @admin.display(description='сума')
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE, verbose_name='Замовлення')
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE, verbose_name='Продукт')
    product_age = models.CharField(max_length=100, verbose_name='Вік рослини')
    product_container = models.CharField(max_length=100, verbose_name='Розмір контейнеру')
    price = models.DecimalField(default=0, max_digits=10, decimal_places=0, verbose_name='Ціна')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Кількість')

    class Meta:
        verbose_name = 'Предмети замовлення'
        verbose_name_plural = 'Предмети замовлення'

    def __str__(self):
        return ''

    def get_cost(self):
        return self.price * self.quantity

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main_app.models import Product

from .cart import Cart

@require_POST
def cart_add(request, product_id, product_age, product_container, product_price):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product=product,
             product_age=product_age,
             product_container=product_container,
             product_price=product_price,
             quantity=1),
    return redirect('cart_detail')


def cart_remove(request, product_id, product_age, product_container):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product, product_age, product_container)
    return redirect('cart_detail')


@require_POST
def cart_recalculate(request, product_id, product_age, product_container, quantity):
    cart = Cart(request)
    cart.recalculate(
        product_id=product_id,
        product_age=product_age,
        product_container=product_container,
        quantity=quantity
    )
    return redirect('cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart_detail.html', {'cart': cart})

cart/templates/cart_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Кошик{% endblock %}

{% block content %}
    <!-- Dynamic cart -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <div class="container mt-10 mb-3 flex-grow-1">
      <div class="row justify-content-center">
        <h3 class="text-center cart-empty">Нажаль Ваш кошик порожній. Зробіть будь-ласка замовлення</h3>
      {% if cart|length %}
        <div class="col-xl-7 col-lg-8 col-md-7">
          <div class="border p-3 totals">
            <h2 class="h6 text-uppercase mb-0">Кошик
                <strong>
                    (<span class="cart-total-length">{{ cart|length }}</span>):
                    <span class="cart-total"> {{ cart.get_total_price }} грн</span>
                </strong>
            </h2>
          </div>
        {% for item in cart %}
            {% with product=item.product %}
              <div class="border p-3 mt-3 clearfix item">
                <div class="row d-flex align-items-center justify-content-center">
                    <div class="col-6 col-lg-2">
                      <a href="{{ product.get_absolute_url }}">
                          <img class="img-fluid h-auto" src="/media/{{ product.images.first }}" alt="{{ product }}">
                      </a>
                    </div>
                    <div class="col-12 col-lg-4 text-center mt-2 mt-lg-0">
                      <h3 class="h6 mb-0">{{ product }}<br>
                        <small>{{ item.product_age.get_product_age_display }}
                            {{ item.product_container.get_product_container_display }}</small>
                          <br>
                        <small>{{ item.price }} грн</small>
                      </h3>
                    </div>
                    <div class="product-price d-none">{{ item.price }}</div>
                    <div class="pass-quantity col-4 col-lg-2 col-md-4 col-sm-3">
                      <label for="pass-quantity" class="pass-quantity">Кількість</label>
                      <input id="pass-quantity" class="form-control w-75" type="number" value="{{ item.quantity }}"
                             min="1" data-product_id="{{ product.id }}"
                             data-product_age="{{ item.product_age.product_age }}"
                             data-product_container="{{ item.product_container.product_container }}"
                      >
                    </div>
                    <div class="col-4 col-lg-2 col-md-2 col-sm-2 product-line-price text-center">
                      <span class="product-line-price">{{ item.total_price }} грн</span>
                    </div>
                    <div class="remove-item col-4 col-lg-2 text-center">
                      <button class="remove-product btn-light"
                              id="search_icon"
                              data-product_id="{{ product.id }}"
                              data-product_age="{{ item.product_age.product_age }}"
                              data-product_container="{{ item.product_container.product_container }}">
                        <i class="far fa-trash-alt"></i>
                      </button>
                    </div>
                  </div>
              </div>
            {% endwith %}
        {% endfor %}
        </div>

        <div class="col-xl-3 col-lg-4 col-md-5 totals">
          <div class="border px-3">
            <div class="border-bottom">
              <p class="text-uppercase mb-0 py-3"><strong>Підсумок замовлення</strong></p>
            </div>
            <div class="totals-item totals-item-total d-flex align-items-center
            justify-content-between pt-3">
              <p class="text-uppercase"><strong>Всього</strong></p>
              <p class="totals-value font-weight-bold cart-total">{{ cart.get_total_price }} грн</p>
            </div>
          </div>
          <a href="{% url 'order_create' %}"
             class="mt-3 btn btn-success w-100 d-flex justify-content-center btn-lg checkout
             {% if cart.get_total_price < 150 %} disabled {% endif %}">
              Оформити замовлення
          </a>
          {% if cart.get_total_price < 150 %}
              <div class="mt-3 alert-danger text-center">
                    Зверніть увагу!
                    <br>
                    Мінімальна сума для оформлення замовлення 150 грн
              </div>
          {% endif %}
        </div>
      {% else %}
          <h3 class="text-center">Нажаль Ваш кошик порожній. Зробіть будь-ласка замовлення</h3>
      {% endif %}
      </div>
    </div><!-- container -->

    <script src="{% static 'js/dynamically_change_cart.js' %}"></script>
{% endblock %}